% MANCHESTER_CODING Encode a sequence of binary bits using Manchester coding
%
% INPUTS:
% bits: a vector of binary bits to be encoded (1s and 0s)
% high_voltage: the voltage level for a logic high bit
% sampling_per_bit: the number of samples per bit
%
% OUTPUTS:
% output_signal: a vector containing the Manchester encoded signal
%
% DESCRIPTION:
% This function encodes a sequence of binary bits using Manchester coding, which is a form of
% differential encoding that is commonly used in digital communication systems. In Manchester coding,
% each bit is represented by a transition between two voltage levels, which allows the receiver to
% recover the clock signal and the data signal simultaneously. The output signal is a waveform that
% can be transmitted over a physical medium, such as a wire or an optical fiber, and decoded at the
% receiving end to recover the original binary data.
%
% The function takes three input arguments: bits, high_voltage, and sampling_per_bit. The bits argument
% is a vector of binary bits to be encoded, where each bit can be either a 1 or a 0. The high_voltage
% argument is the voltage level for a logic high bit, which is typically set to the maximum voltage
% that can be transmitted over the physical medium. The sampling_per_bit argument is the number of
% samples per bit, which determines the temporalresolution of the encoded signal.
%
% The function returns a vector containing the Manchester encoded signal, which can be plotted or
% transmitted over a physical medium. The output signal is generated by encoding each bit using a
% positive or a negative pulse, depending on whether the bit is a 1 or a 0. Each pulse is half the
% duration of a bit, and is followed by a pulse of the opposite polarity to represent the transition
% between the two voltage levels. The output signal is a waveform that alternates between high_voltage
% and -high_voltage, and can be transmitted over a physical medium using a suitable modulation scheme.
%
% If the sampling_per_bit argument is not provided, the function sets it to a default value of 100.
% The function also plots the encoded signal in a new figure, along with a grid and axis labels.

function output_signal = manchester_coding(bits, high_voltage, sampling_per_bit)
    % SPLIT_PHASE_ENCODING Encode a sequence of binary bits using Split Phase (Manchester) encoding
    %
    % INPUTS:
    %   bits: a vector of binary bits to be encoded (1s and 0s)
    %   high_voltage: the voltage level for a logic high bit
    %   low_voltage: the voltage level for a logic low bit
    %   sampling_per_bit: the number of samples per bit
    %
    % OUTPUTS:
    %   output_signal: a vector containing the Split Phase (Manchester) encoded signal

    % Check the input arguments
    if nargin < 3
        sampling_per_bit = 100;
    end

    % Compute the number of samples in the waveform
    num_samples = length(bits) * sampling_per_bit;

    % Initialize the output signal
    output_signal = zeros(1, num_samples);

    % Compute the pulse width for the Manchester pulse
    pulse_width = sampling_per_bit / 2;

    % Generate the Manchester pulse waveform
    for i = 1:length(bits)
        if bits(i) == 1
            % Encode a "1" bit as a positive pulse followed by a negative pulse
            output_signal((i-1)*sampling_per_bit + 1:(i-1)*sampling_per_bit+ pulse_width) = high_voltage;
            output_signal((i-1)*sampling_per_bit + pulse_width + 1:i*sampling_per_bit) = -high_voltage;
        else
            % Encode a "0" bit as a negative pulse followed by a positive pulse
            output_signal((i-1)*sampling_per_bit + 1:(i-1)*sampling_per_bit + pulse_width) = -high_voltage;
            output_signal((i-1)*sampling_per_bit + pulse_width + 1:i*sampling_per_bit) = high_voltage;
        end
    end

    % Create a new figure
    figure();
    
    % Create the time axis
    t = linspace(0, length(output_signal)/sampling_per_bit, length(output_signal));
    
    % Plot the signal
    plot(t, output_signal);
    axis([0 t(end) -1.2*high_voltage 1.2*high_voltage]);
    
    % Add grid and labels
    grid on;
    xlabel('Time (s)');
    ylabel('Voltage (V)');
    title('Manchester Coding');
end